name: Build Application

on:
  push:
    tags: # Trigger on new tags like v1.0.0, v1.2.3 etc.
      - "v*"
  workflow_dispatch: # Allows manual triggering

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.read_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for go-winres to get git tags for versioning if needed

      - name: Read version from VERSION file or Git tag
        id: read_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            APP_VERSION="${{ github.ref_name }}"
            # Remove 'v' prefix if present
            APP_VERSION="${APP_VERSION#v}"
          elif [[ -f VERSION ]]; then
            APP_VERSION=$(cat VERSION)
          else
            APP_VERSION="0.0.0-dev"
          fi
          echo "App version: $APP_VERSION"
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: read-version # Depends on the version being read
    strategy:
      matrix:
        os_config:
          - os_runner: ubuntu-22.04
            goos: linux
            goarch: amd64
            deps: "sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev"
            output_suffix: "_linux_amd64"
            # Use shell variables $APP_NAME and $APP_VERSION here
            build_cmd: 'CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags=''-s -w'' -o "$APP_NAME_$APP_VERSION${{ matrix.os_config.output_suffix }}" main.go'

          - os_runner: macos-latest
            goos: darwin
            goarch: amd64
            deps: ""
            output_suffix: "_macos_amd64.zip"
            # macOS build is handled differently in the run step, no build_cmd here

          - os_runner: windows-latest
            goos: windows
            goarch: amd64
            # Use shell variable $APP_VERSION here. ${{ github.run_number }} is fine as 'github' context is available.
            deps: 'go install github.com/tc-hib/go-winres@latest && go-winres make --product-version "$APP_VERSION" --file-version "$APP_VERSION.${{ github.run_number }}" --arch amd64 -rc platform/windows/windows.rc'
            output_suffix: "_windows_amd64.exe"
            # Use shell variables $APP_NAME and $APP_VERSION here
            build_cmd: 'CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags=''-s -w -H windowsgui'' -o "$APP_NAME_$APP_VERSION${{ matrix.os_config.output_suffix }}" main.go'

    runs-on: ${{ matrix.os_config.os_runner }}
    env:
      APP_NAME: AgentSmith
      APP_VERSION: ${{ needs.read-version.outputs.app_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2" # This specific version should be fine

      - name: Tidy Go modules
        run: go mod tidy
        shell: bash

      - name: Set BUILD_NUMBER (for macOS Info.plist)
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # Combined Build Step using matrix strategy
      - name: Install Dependencies & Build
        run: |
          if [[ -n "${{ matrix.os_config.deps }}" ]]; then
            echo "--- Installing dependencies for ${{ matrix.os_config.goos }} ---"
            ${{ matrix.os_config.deps }} # Shell variables within deps will be expanded here
          fi

          echo "--- Building for ${{ matrix.os_config.goos }}/${{ matrix.os_config.goarch }} ---"
          if [[ "${{ matrix.os_config.goos }}" == "darwin" ]]; then
            # macOS specific build and bundling
            # Using ${{ env.VAR }} here is fine because this is a 'run' step script
            sed -i '' "s/__VERSION__/${{ env.APP_VERSION }}/g" platform/macos/Info.plist
            sed -i '' "s/__BUILD_NUMBER__/${{ env.BUILD_NUMBER }}/g" platform/macos/Info.plist
            
            CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o "${{ env.APP_NAME }}_binary" main.go

            APP_BUNDLE_NAME="${{ env.APP_NAME }}.app" # Uses shell expansion of env var
            mkdir -p "${APP_BUNDLE_NAME}/Contents/MacOS"
            mkdir -p "${APP_BUNDLE_NAME}/Contents/Resources"
            
            mv "${{ env.APP_NAME }}_binary" "${APP_BUNDLE_NAME}/Contents/MacOS/${{ env.APP_NAME }}"
            cp platform/macos/Info.plist "${APP_BUNDLE_NAME}/Contents/Info.plist"
            cp assets/icon.icns "${APP_BUNDLE_NAME}/Contents/Resources/icon.icns"
            
            zip -r "${{ env.APP_NAME }}_${{ env.APP_VERSION }}${{ matrix.os_config.output_suffix }}" "${APP_BUNDLE_NAME}"
          else
            # Generic build command for Linux/Windows
            # Shell variables within build_cmd will be expanded here
            ${{ matrix.os_config.build_cmd }}
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Using ${{ env.VAR }} here is fine as these are step inputs
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}-${{ matrix.os_config.goos }}-${{ matrix.os_config.goarch }}
          path: |
            ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_linux_amd64
            ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_windows_amd64.exe
            ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_macos_amd64.zip
          if-no-files-found: error
